name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Go to Backend Dir
      run: cd backend/
    - name: pwd dir
      run: pwd
    - name: Run yarn again
      run: yarn
    - name: Run tests
      run: yarn run test
