name: frontend-lint

on:
  pull_request

jobs:
  PullRequestCheck:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.1'
      - cd frontend && yarn && yarn run lint